# 어떤 작업인지 이름달기

name: 나의 첫 CI

# 언제 실행하는지
on: [push]

# 어떤 작업할지 알려줘!
jobs:
  helloprint:
    runs-on: ubuntu-latest
    steps:
      - run: echo "가져오기 전"
      - run: ls

      # 코드 가져오는 걸 맡길께!
      # actions/checkout
      - uses: actions/checkout@v6
      - run: echo "가져온 후"
      - run: ls

        